### ISSUE TITLE
Screenshoots saved with less quality

### ISSUE THREAD

**Issue by Readun** [hantabaru1014/ResoniteScreenshotExtensions#1]
I noticed that screenshoots beeing saved in a way lower quality with this mod, all options can be disabled and it will still save the lesser quality. Only removing it bringing it back up to the Original.

Size difference
With mod: 100-200 kb
Without: 1-5 mb

Zoomed in comparison, left without, right with mod.
![grafik](https://github.com/hantabaru1014/ResoniteScreenshotExtensions/assets/76232047/da089e3a-55f7-4353-9641-e42720dfaa49)

Both saved as 2560x1440 through the Resolutions mod, if that might have an impact?

PS: https://github.com/LeCloutPanda/Resolutions

**Comment by hantabaru1014** [comment]
Thanks for your report!
Fixed in [v1.1.0](https://github.com/hantabaru1014/ResoniteScreenshotExtensions/releases/tag/v1.1.0). (In webp, I also made it possible to set the quality!)
