### ISSUE TITLE
No saved Screenshoots

### ISSUE THREAD

**Issue by Readun** [hantabaru1014/ResoniteScreenshotExtensions#3]
After the last update, it seems like this mod causes screenshoots to not be saved at all. 
(Rip roughly 100 pictures (〒▽〒) )

**Comment by hantabaru1014** [comment]
oh, sorry!
I fixed it in v1.1.3. and add error handling
https://github.com/hantabaru1014/ResoniteScreenshotExtensions/releases/tag/v1.1.3

(As you probably know, screenshots should also be saved on Steam, so please recover them from there...)

**Comment by Readun** [comment]
Thanks!
> (As you probably know, screenshots should also be saved on Steam, so please recover them from there...)

I.. did turn that off to save space and not have the hitches ^^`

**Comment by hantabaru1014** [comment]
Yeah... I thought that might be the case. I am the same way orz
